### PR TITLE
Allow for anycase SHA256 HTTP header

### PR DESCRIPTION
**Pull request by ca-monteiro**
- [ ] This pull request is created in the [jfrog/jenkins-jfrog-plugin](https://github.com/jfrog/jenkins-jfrog-plugin) repository.

### CODE REVIEW

**Comment by ca-monteiro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ca-monteiro** [comment]
recheck

**Comment by ca-monteiro** [comment]
recheckcla

**Review by yahavi — APPROVED** [review]
Appreciate your contribution, @ca-monteiro!
That looks fantastic.

**Pull request merged**
